language: cpp
matrix:
  include:
  - name: Linux (Qt4)
    os: linux
    dist: xenial
    before_install:
    - sudo apt update -qq
    - sudo apt install build-essential
    - sudo apt install qt4-default
    compiler:
    - gcc
    script:
    - qmake CONFIG+=release QPortKnocking.pro
    - make -j4
    - make clean
    - qmake CONFIG+=debug QPortKnocking.pro
    - make -j4
  - name: Linux (Qt5)
    os: linux
    dist: xenial
    before_install:
    - sudo apt update -qq
    - sudo apt install build-essential
    - sudo apt install qt5-default
    compiler:
    - gcc
    script:
    - qmake CONFIG+=release QPortKnocking.pro
    - make -j4
    - make clean
    - qmake CONFIG+=debug QPortKnocking.pro
    - make -j4
  #- name: OSX (Qt4)
  #  os: osx
  #  osx_image: xcode7.2
  #  before_install:
  #  - brew tap cartr/qt4
  #  - brew tap-pin cartr/qt4
  #  - brew install qt@4
  #  script:
  #  - qmake -spec macx-xcode QPortKnocking.pro
  #  - xcodebuild -list -project QPortKnocking.xcodeproj
  #  - xcodebuild -scheme QPortKnocking build
  #- name: OSX (Qt5)
  #  os: osx
  #  osx_image: xcode7.2
  #  before_install:
  #  - brew install qt5
  #  - brew link qt5 --force
  #  script:
  #  - qmake -spec macx-xcode QPortKnocking.pro
  #  - xcodebuild -list -project QPortKnocking.xcodeproj
  #  - xcodebuild -scheme QPortKnocking build
