language: cpp
matrix:
  include:
  - os: linux
    dist: xenial
    before_install:
    - sudo apt update -qq
    - sudo apt install build-essential
    - sudo apt install qtdeclarative5-dev qt5-default
    compiler:
    - clang
    - gcc
    script:
    - echo $TRAVIS_TAG
    - qmake QPortKnocking.pro
    - make -j4
  - os: osx
    osx_image: xcode7.2
    before_install:
    - brew install qt5
    - brew link qt5 --force
    script:
    - qmake -spec macx-xcode QPortKnocking.pro
    - xcodebuild -list -project QPortKnocking.xcodeproj
    - xcodebuild -scheme QPortKnocking build
