language: cpp
matrix:
  include:
  - name: Linux (Qt4)
    os: linux
    dist: xenial
    before_install:
    - sudo apt update -qq
    - sudo apt install build-essential
    - sudo apt install qt4-default
    # Dependency for test coverage
    - sudo apt install python3-pip
    - sudo pip3 install codecov
    compiler:
    - g++
    script:
    # Build library and test in release
    - qmake CONFIG+=release QPortKnocking.pro
    - make
    # Build library and test in debug
    - make clean -j4
    - qmake CONFIG+=debug QPortKnocking.pro
    - make
    # Launch test
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib/
    - export LD_LIBRARY_PATH
    - ./test/test
    # Launch test coverage (in linux debug mode only)
    - sudo gcov -n -o . lib/src/QPortKnocking.cpp > /dev/null
    - codecov > /dev/null
    after_success:
    # Push code coverage result into codecov.io
    - bash <(curl -s https://codecov.io/bash)
  - name: Linux (Qt5)
    os: linux
    dist: xenial
    before_install:
    - sudo apt update -qq
    - sudo apt install build-essential
    - sudo apt install qt5-default
    compiler:
    - g++
    script:
    - qmake CONFIG+=release QPortKnocking.pro
    - make
    - make clean -j4
    - qmake CONFIG+=debug QPortKnocking.pro
    - make
  #- name: OSX (Qt4)
  #  os: osx
  #  osx_image: xcode7.2
  #  before_install:
  #  - brew tap cartr/qt4
  #  - brew tap-pin cartr/qt4
  #  - brew install qt@4
  #  script:
  #  - qmake -spec macx-xcode QPortKnocking.pro
  #  - xcodebuild -list -project QPortKnocking.xcodeproj
  #  - xcodebuild -scheme QPortKnocking build
  #- name: OSX (Qt5)
  #  os: osx
  #  osx_image: xcode7.2
  #  before_install:
  #  - brew install qt5
  #  - brew link qt5 --force
  #  script:
  #  - qmake -spec macx-xcode QPortKnocking.pro
  #  - xcodebuild -list -project QPortKnocking.xcodeproj
  #  - xcodebuild -scheme QPortKnocking build
